import Head from "next/head";
import { Header } from '../components/Header/Header';
import style from '../styles/PageActive.module.scss';
import { CardActive } from "@/components/ui/Cards/Cards";
import { useState, useEffect, use } from "react";
import { PropsDataActive } from '../types/PropsActive'
import { getActive, updateActive } from '../controller/requestApi'
import { ModalActive } from '../components/Modal/modalActive'

export default function pageActive() {

    const [data, setData] = useState<PropsDataActive[]>([]);
    const [loading, setLoading] = useState<boolean>(true);
    const [modalOpen, setModalOpen] = useState<boolean>(false);

    useEffect(() => {

        async function handle() {
            const result = await getActive();
            setData(result);
            setLoading(false);
        }

        handle();
    }, []);



    return (
        <>
            <Head>
                <title>Active</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="#" />
            </Head>

            <main className={style.containerGeneral}>


                {
                  modalOpen && <ModalActive />
                }


                <Header />

                <section className={style.containerCardActive}>
                    {loading ? "Carregando..." : data.map(item => {
                        return (
                            <CardActive key={item.ativo} {...item} />
                        )
                    })}
                </section>
            </main>
        </>
    )
}