import Head from "next/head";
import { Header } from "@/components/Header/Header";
import { useEffect } from "react";
import { updateActive } from '../controller/requestApi'
export default function Home() {

  useEffect(() => {
    async function handelServiceApi() {
      await updateActive();
    }

    handelServiceApi()
  }, [])

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header></Header>
      </main>
    </>
  );
}
