import Head from "next/head";
import { Header } from '../components/Header/Header'

export default function pageActive() {
    return (

        <>
            <Head>
                <title>My wallet</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="#" />
            </Head>

            <main>
                <Header />
            </main>
        </>
    )
}